### ISSUE TITLE
How to make it work

### ISSUE THREAD

**Issue by Jaylon2022** [Azure/Remote-Desktop-Services-Protocol-Sample#2]
I registered it as shown in this topic, restarted Remote Desktop Services and nothing have happened! Then, I've tried to rewrite LoadableProtocol_Object value of Rdp-Tcp key to CLSID of my COM-class. Nothing happened again! When I'm trying to create my ProtocolManager by hands using CoCreateInstance, I works as expected, but how can I make Terminal Services do the same? There are no errors in Event Viewer, no message boxes with information of what i'm doing wrong. Please, publish more detailed information of creating and registering protocol providers, if possible.

![image](https://user-images.githubusercontent.com/12760416/184822239-825afe62-1b4b-4a2b-af53-b610d3fcdb7d.png)

**Comment by ignazp** [comment]
I reproduced the same issue by following the documentation.
No log message is reported in the Event Viewer.
We tried to add some custom log messages, but no log file has been created..
@guscatalano can you provide some information about this issue?

**Comment by ignazp** [comment]
I was able to solve the issue by adding also a `DWORD` named `fEnableWinstation` with value `1`

**Comment by Resulte** [comment]
我通过`regsvr32 TestProtocol_Ext.dll`注册成功了COM，并且注册表也修改了：
I successfully registered the COM using `regsvr32 TestProtocol_Ext.dll`, and the registry was also modified:
<img width="980" height="177" alt="Image" src="https://github.com/user-attachments/assets/935bf093-36d9-433e-91ec-a4882c1a4a7f" />
然后我也重启了termService，但是还是没有生效，自定义的日志也没有任何输出。
求教一下这是为什么，该如何解决？
Then I also restarted the termService, but it still didn't take effect, and the custom log didn't have any output either.
Could you please advise why this is happening and how to solve it?

@Jaylon2022 @ignazp
